1 compilation error from upgrade to 2020.3.12f1 LTS
* SampleInputManager.cs in Assets\SceneUnderstanding\Examples\STandardAssets\Scripts\ throws error on line 358, character 40
  * "error CS0246: The type or namespace name 'TappedEventArgs' could not be found (are you missing a using directive or an assembly reference?)
  * redefining TappedEventArgs with an empty class throws more errors from dependencies and references